#!/usr/bin/env bash

# Check if this is the initial commit
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Use git diff-index to check for whitespace errors
if ! git diff-index --check --cached $against
then
    echo "Aborting commit due to whitespace errors."
    exit 1
else
    # Fail on first line that fails.
    set -e

    NEW_FILES=$(git --no-pager diff --name-only --cached --diff-filter=d)
    JS_FILES=$(echo "$NEW_FILES" | { grep .js$ || true; })
    SNAPSHOT_FILES=$(echo "$NEW_FILES" | { grep .snap$ || true; })

    if [ -n "$JS_FILES" ];
    then
        npm run linter:js -s -- $JS_FILES
    fi

    if [ -n "$JS_FILES" ] || [ -n "$SNAPSHOT_FILES" ];
    then
        npm run test -s
    fi

    exit 0
fi
